spring:
  application:
    name: identity-service

  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5433/identity_db
    driver-class-name: org.postgresql.Driver
    username: devuser
    password: devpass

  jpa:
    hibernate:
      ddl-auto: none  # Let Liquibase handle schema, not JPA
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.yaml

server:
  servlet:
    context-path: /api

management:
  tags:
    application: identity-service
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
