databaseChangeLog:
  - changeSet:
      id: 005-create-client-application-table
      author: Åsa Wegelius
      changes:
        - createTable:
            tableName: client_application
            columns:
              - column:
                  name: application_id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false
                  defaultValueComputed: gen_random_uuid()
              - column:
                  name: client_id
                  type: UUID
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: created_at
                  type: TIMESTAMPTZ
                  defaultValueComputed: now()
                  constraints:
                    nullable: false

        - addForeignKeyConstraint:
            baseTableName: client_application
            baseColumnNames: client_id
            constraintName: fk_application_client
            referencedTableName: system_client
            referencedColumnNames: client_id
            onDelete: CASCADE

        - createIndex:
            tableName: client_application
            indexName: idx_client_application_id
            columns:
              - column:
                  name: application_id

        - createIndex:
            tableName: client_application
            indexName: idx_client_application_client_id
            columns:
              - column:
                  name: client_id
