databaseChangeLog:
  - changeSet:
      id: 007-create-client-application-grant-type-table
      author: Åsa Wegelius
      changes:
        - createTable:
            tableName: client_application_grant_type
            columns:
              - column:
                  name: id
                  type: UUID
                  constraints:
                    primaryKey: true
                    nullable: false
                  defaultValueComputed: gen_random_uuid()
              - column:
                  name: application_id
                  type: UUID
                  constraints:
                    nullable: false
              - column:
                  name: grant_type
                  type: VARCHAR(64)
                  constraints:
                    nullable: false

        - addForeignKeyConstraint:
            baseTableName: client_application_grant_type
            baseColumnNames: application_id
            constraintName: fk_grant_type_app
            referencedTableName: client_application
            referencedColumnNames: application_id
            onDelete: CASCADE

        - createIndex:
            tableName: client_application_grant_type
            indexName: idx_grant_type_id
            columns:
              - column:
                  name: id

        - createIndex:
            tableName: client_application_grant_type
            indexName: idx_grant_type_application_id
            columns:
              - column:
                  name: application_id
